### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by liamdebeasi** [willmartindev/div.js#14]
@willmartian I am trying to use a non-div element in my div.js app, but it's not working. Please fix this!

**Comment by willmartian** [comment]
RE: Cease and desist from [stalking/harassing/etc.]
Dear @liamdebeasi:
This CEASE AND DESIST ORDER is to inform you that your persistent actions including but not limited to [insert actions here (example: calling me in the middle of the night and hanging up, waiting outside my house, etc)] have become unbearable. You are ORDERED TO STOP such activities immediately as they are being done in violation of the law.
I have the right to remain free from these activities as they constitute [harassment/stalking/etc.], and I will pursue any legal remedies available to me against you if these activities continue. These remedies include but are not limited to: contacting law enforcement to obtain criminal sanctions against you, and suing you civilly for damages I have incurred as a result of your actions.
Again, you must IMMEDIATELY STOP [unwanted activities] and send me written confirmation that you will stop such activities. You risk incurring some very severe legal consequences if you fail to comply with this demand.
This letter acts as your final warning to discontinue this unwanted conduct before I pursue legal actions against you. At this time, I am not contacting the authorities or filing civil suit against you, as I hope we can resolve this matter without authoritative involvement. I am not under any circumstances, however, waiving any legal rights I have presently, or future legal remedies against you by sending you this letter. This order acts as ONE FINAL CHANCE for you to cease your illegal activities before I exercise my rights.
To ensure compliance with this letter, and to halt any legal action I may take against you, I require you to fill in and sign the attached form and mail it back to me within 10 days of your receipt of this letter. Failure to do so will act as evidence of your infringement upon my legal rights, and I will immediately seek legal avenues to remedy the situation.
Sincerely,
[your signature]___[your printed name]
CEASE AND DESIST COMPLIANCE AGREEMENT
I, [insert perpetrator’s name here] do hereby agree to stop [insert unwanted activities here] which are in violation of [your full name]’s rights. I understand that this is my final chance to cease these activities. I understand that [your full name] potentially has the right to pursue legal action against me relating to my engagement in these activities, but [he/she] will not pursue those rights in contemplation of my compliance with this written demand. I further understand that [your full name] has not waived [his/her] rights and may pursue legal remedies against me if I fail to abide by this agreement. I understand that this agreement is not specifically limited to the activities named herein. I will not engage in any activity now or in the future done for the purpose of [stalking/harassing] [your full name]. I furthermore agree not to engage in any activity, regardless of its official title, that is done in violation of [your full name]’s legal rights. If I fail to cease performing these activities, [your full name] may pursue legal action against me in accordance [his/her] legal rights. This agreement acts as a contract between [perpetrator’s name] and [your full name]. Forbearing enforcement of legally enforceable remedies is sufficient consideration to support this agreement. This agreement represents the entire agreement between the parties. Any statements made orally, written, or otherwise which are not contained herein shall have no impact on either parties’ rights or obligations elaborated in this agreement.
Date ____________________
________________________[perpetrator’s printed name]
________________________[perpetrator’s signature]

**Comment by liamdebeasi** [comment]
@willmartian any update?

**Comment by willmartian** [comment]
Hey there @liamdebeasi, thanks for reaching out! Try using our official CLI for div.js and let me know if that helps:

`npx jamstack`

Please direct any future questions to the Linux kernel mailing list.

**Comment by piemadd** [comment]
poop
